name: DAST - OWASP ZAP Full Scan (canonicalization-example)

on:
  workflow_dispatch:  # run it manually from the Actions tab

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./canonicalization-example
        run: npm install

      - name: Start application
        working-directory: ./canonicalization-example
        run: |
          npm start &
          sleep 25   # wait for the app to start

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: "http://localhost:3000"
          cmd_options: "-a"
